version: '3.3'
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "lessons"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "qwe123"
    volumes:
      - mongo:/data/db
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
 #     ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123
  #    ME_CONFIG_MONGODB_URL: mongodb://root:qwe123@mongo:27017/
volumes:
  mongo: